"""empty message

Revision ID: 67020b0a7f7a
Revises: 
Create Date: 2022-01-06 16:59:52.198501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67020b0a7f7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('is_borrowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('is_borrowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
