"""removed is_borrowed column

Revision ID: 93fd47bcd8c7
Revises: 67020b0a7f7a
Create Date: 2022-01-07 13:17:34.226176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fd47bcd8c7'
down_revision = '67020b0a7f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('is_borrowed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_borrowed', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
